# CMake generated Testfile for 
# Source directory: /work/hw-echen606/hw2/hw2_tests/cmdhandler_tests
# Build directory: /work/hw-echen606/hw2/hw2_tests/cmdhandler_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Cmdhandlers.AndHandler "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/cmdhandler_tests" "--gtest_filter=Cmdhandlers.AndHandler")
set_tests_properties(Cmdhandlers.AndHandler PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;0;")
add_test(Cmdhandlers.OrHandler "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/cmdhandler_tests" "--gtest_filter=Cmdhandlers.OrHandler")
set_tests_properties(Cmdhandlers.OrHandler PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;0;")
add_test(Cmdhandlers.DiffHandler "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/cmdhandler_tests" "--gtest_filter=Cmdhandlers.DiffHandler")
set_tests_properties(Cmdhandlers.DiffHandler PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;0;")
add_test(Cmdhandlers.IncomingHandler "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/cmdhandler_tests" "--gtest_filter=Cmdhandlers.IncomingHandler")
set_tests_properties(Cmdhandlers.IncomingHandler PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;0;")
add_test(Cmdhandlers.OutgoingHandler "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/cmdhandler_tests" "--gtest_filter=Cmdhandlers.OutgoingHandler")
set_tests_properties(Cmdhandlers.OutgoingHandler PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/cmdhandler_tests/CMakeLists.txt;0;")
