# CMake generated Testfile for 
# Source directory: /work/hw-echen606/hw2/hw2_tests/mdparser_tests
# Build directory: /work/hw-echen606/hw2/hw2_tests/mdparser_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Parsers.MdParserSpecialStart "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MdParserSpecialStart")
set_tests_properties(Parsers.MdParserSpecialStart PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
add_test(Parsers.MdParserSpecialEnd "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MdParserSpecialEnd")
set_tests_properties(Parsers.MdParserSpecialEnd PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
add_test(Parsers.MdParserSpecialMiddle "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MdParserSpecialMiddle")
set_tests_properties(Parsers.MdParserSpecialMiddle PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
add_test(Parsers.MdParserTextFull "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MdParserTextFull")
set_tests_properties(Parsers.MdParserTextFull PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
add_test(Parsers.MdParserLinksSepStart "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MdParserLinksSepStart")
set_tests_properties(Parsers.MdParserLinksSepStart PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
add_test(Parsers.MdParserLinksSepEnd "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MdParserLinksSepEnd")
set_tests_properties(Parsers.MdParserLinksSepEnd PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
add_test(Parsers.MdParserLinksSepMiddle "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MdParserLinksSepMiddle")
set_tests_properties(Parsers.MdParserLinksSepMiddle PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
add_test(Parsers.MdParserLinksFull "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MdParserLinksFull")
set_tests_properties(Parsers.MdParserLinksFull PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
add_test(Parsers.MDWriteupCornerCases "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MDWriteupCornerCases")
set_tests_properties(Parsers.MDWriteupCornerCases PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
add_test(Parsers.MDAnchorAnchor "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/mdparser_tests/mdparser_tests" "--gtest_filter=Parsers.MDAnchorAnchor")
set_tests_properties(Parsers.MDAnchorAnchor PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;3;add_source_problem;/work/hw-echen606/hw2/hw2_tests/mdparser_tests/CMakeLists.txt;0;")
