# CMake generated Testfile for 
# Source directory: /work/hw-echen606/hw2/hw2_tests/searcheng_tests
# Build directory: /work/hw-echen606/hw2/hw2_tests/searcheng_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SearchEng.ParserRegistration "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/searcheng_tests/searcheng_tests" "--gtest_filter=SearchEng.ParserRegistration")
set_tests_properties(SearchEng.ParserRegistration PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;0;")
add_test(SearchEng.ReadPageMultipleTimes "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/searcheng_tests/searcheng_tests" "--gtest_filter=SearchEng.ReadPageMultipleTimes")
set_tests_properties(SearchEng.ReadPageMultipleTimes PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;0;")
add_test(SearchEng.ANDCombiner "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/searcheng_tests/searcheng_tests" "--gtest_filter=SearchEng.ANDCombiner")
set_tests_properties(SearchEng.ANDCombiner PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;0;")
add_test(SearchEng.ORCombiner "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/searcheng_tests/searcheng_tests" "--gtest_filter=SearchEng.ORCombiner")
set_tests_properties(SearchEng.ORCombiner PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;0;")
add_test(SearchEng.DiffCombiner "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/searcheng_tests/searcheng_tests" "--gtest_filter=SearchEng.DiffCombiner")
set_tests_properties(SearchEng.DiffCombiner PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;0;")
add_test(SearchEng.RetrievePage "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/searcheng_tests/searcheng_tests" "--gtest_filter=SearchEng.RetrievePage")
set_tests_properties(SearchEng.RetrievePage PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;0;")
add_test(SearchEng.LinkCornerCases "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/searcheng_tests/searcheng_tests" "--gtest_filter=SearchEng.LinkCornerCases")
set_tests_properties(SearchEng.LinkCornerCases PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;0;")
add_test(SearchEng.SameLink "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/searcheng_tests/searcheng_tests" "--gtest_filter=SearchEng.SameLink")
set_tests_properties(SearchEng.SameLink PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;0;")
add_test(SearchEng.DisplayPage "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-echen606/hw2/hw2_tests/searcheng_tests/searcheng_tests" "--gtest_filter=SearchEng.DisplayPage")
set_tests_properties(SearchEng.DisplayPage PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/CustomTests.cmake;47;add_test;/work/hw-echen606/hw2/hw2_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;6;add_source_problem;/work/hw-echen606/hw2/hw2_tests/searcheng_tests/CMakeLists.txt;0;")
